version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - main
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend: &backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /scripts/start_prod.sh
    networks:
      - main
    volumes:
      - ./backend:/code
      - django-static:/code/static
    depends_on:
      - postgres
    env_file:
      - ./.env.prod

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx/prod/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - main
    build:
      context: .
      dockerfile: frontend/nginx/prod/Dockerfile

volumes:
  django-static:
  pg-data:

networks:
  main:
    driver: bridge
